# Generated by Django 3.0.4 on 2020-03-18 11:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('visitorsfront', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=200),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 18, 11, 28, 38, 868545, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 18, 11, 28, 38, 868545, tzinfo=utc)),
        ),
    ]
